export const breakPoints_px = {
  TAB_SCREEN: "949px",
  TAB_SCREEN_SMALL: "740px",
  MOBILE_SCREEN: "550px",
  MOBILE_SCREEN_SMALL: "390px",
  STANDARD_DESKTOP_SCREEN: "1450px",
};

export const breakPoints = {
  TAB_SCREEN: 949,
  TAB_SCREEN_SMALL: 740,
  MOBILE_SCREEN: 550,
  MOBILE_SCREEN_SMALL: 390,
  STANDARD_DESKTOP_SCREEN: 1450,
};
