export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";
export const SET_INPUT_EMAIL_ADDRESS = "SET_INPUT_EMAIL_ADDRESS";
export const SET_PASSWORD = "SET_PASSWORD";
export const SET_IS_INPUT_EMAIL_ERROR = "SET_IS_INPUT_EMAIL_ERROR";
export const SET_IS_INPUT_PASSWORD_ERROR = "SET_IS_INPUT_PASSWORD_ERROR";
